///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestExpoDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FastFeedback recording.
    /// </summary>
    [TestModule("c2c1f5a8-3ca9-47f5-b91b-e448460f30f8", ModuleType.Recording, 1)]
    public partial class FastFeedback : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestExpoDemoRepository repository.
        /// </summary>
        public static TestExpoDemoRepository repo = TestExpoDemoRepository.Instance;

        static FastFeedback instance = new FastFeedback();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FastFeedback()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FastFeedback Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'www.ranorex.com' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("www.ranorex.com", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestAutomationForGUITestingRanore.DownloadTrialButton' at 96;18.", repo.TestAutomationForGUITestingRanore.DownloadTrialButtonInfo, new RecordItemIndex(1));
            repo.TestAutomationForGUITestingRanore.DownloadTrialButton.Click("96;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestAutomationForGUITestingRanore.FormFirstName' at 68;34.", repo.TestAutomationForGUITestingRanore.FormFirstNameInfo, new RecordItemIndex(2));
            repo.TestAutomationForGUITestingRanore.FormFirstName.Click("68;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}J{LShiftKey up}ohn' with focus on 'TestAutomationForGUITestingRanore.FormFirstName'.", repo.TestAutomationForGUITestingRanore.FormFirstNameInfo, new RecordItemIndex(3));
            repo.TestAutomationForGUITestingRanore.FormFirstName.PressKeys("{LShiftKey down}J{LShiftKey up}ohn");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestAutomationForGUITestingRanore.FormLastName' at 66;21.", repo.TestAutomationForGUITestingRanore.FormLastNameInfo, new RecordItemIndex(4));
            repo.TestAutomationForGUITestingRanore.FormLastName.Click("66;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}D{LShiftKey up}oe' with focus on 'TestAutomationForGUITestingRanore.FormLastName'.", repo.TestAutomationForGUITestingRanore.FormLastNameInfo, new RecordItemIndex(5));
            repo.TestAutomationForGUITestingRanore.FormLastName.PressKeys("{LShiftKey down}D{LShiftKey up}oe");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestAutomationForGUITestingRanore.FormEmail' at 161;35.", repo.TestAutomationForGUITestingRanore.FormEmailInfo, new RecordItemIndex(6));
            repo.TestAutomationForGUITestingRanore.FormEmail.Click("161;35");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'john' with focus on 'TestAutomationForGUITestingRanore.FormEmail'.", repo.TestAutomationForGUITestingRanore.FormEmailInfo, new RecordItemIndex(7));
            repo.TestAutomationForGUITestingRanore.FormEmail.PressKeys("john");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}doe.com' with focus on 'TestAutomationForGUITestingRanore.FormEmail'.", repo.TestAutomationForGUITestingRanore.FormEmailInfo, new RecordItemIndex(8));
            repo.TestAutomationForGUITestingRanore.FormEmail.PressKeys("{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}doe.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestAutomationForGUITestingRanore.Register' at 95;9.", repo.TestAutomationForGUITestingRanore.RegisterInfo, new RecordItemIndex(9));
            repo.TestAutomationForGUITestingRanore.Register.Click("95;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Tell us more about yourself ...') on item 'TestAutomationForGUITestingRanore.TellUsMoreAboutYourself'.", repo.TestAutomationForGUITestingRanore.TellUsMoreAboutYourselfInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.TestAutomationForGUITestingRanore.TellUsMoreAboutYourselfInfo, "InnerText", "Tell us more about yourself ...");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestAutomationForGUITestingRanore.IconExit' at 2;8.", repo.TestAutomationForGUITestingRanore.IconExitInfo, new RecordItemIndex(11));
            repo.TestAutomationForGUITestingRanore.IconExit.Click("2;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestAutomationForGUITestingRanore1.Close' at 16;8.", repo.TestAutomationForGUITestingRanore1.CloseInfo, new RecordItemIndex(12));
            repo.TestAutomationForGUITestingRanore1.Close.Click("16;8");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
