///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestExpoDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestExpoDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("d0e0079b-6379-4f58-878e-815af3a51486")]
    public partial class TestExpoDemoRepository : RepoGenBaseFolder
    {
        static TestExpoDemoRepository instance = new TestExpoDemoRepository();
        TestExpoDemoRepositoryFolders.TestAutomationForGUITestingRanoreAppFolder _testautomationforguitestingranore;
        TestExpoDemoRepositoryFolders.TestAutomationForGUITestingRanore1AppFolder _testautomationforguitestingranore1;

        /// <summary>
        /// Gets the singleton class instance representing the TestExpoDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("d0e0079b-6379-4f58-878e-815af3a51486")]
        public static TestExpoDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestExpoDemoRepository() 
            : base("TestExpoDemoRepository", "/", null, 0, false, "d0e0079b-6379-4f58-878e-815af3a51486", ".\\RepositoryImages\\TestExpoDemoRepositoryd0e0079b.rximgres")
        {
            _testautomationforguitestingranore = new TestExpoDemoRepositoryFolders.TestAutomationForGUITestingRanoreAppFolder(this);
            _testautomationforguitestingranore1 = new TestExpoDemoRepositoryFolders.TestAutomationForGUITestingRanore1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d0e0079b-6379-4f58-878e-815af3a51486")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The TestAutomationForGUITestingRanore folder.
        /// </summary>
        [RepositoryFolder("07b82945-4f59-4eb8-a006-10e9904e3f63")]
        public virtual TestExpoDemoRepositoryFolders.TestAutomationForGUITestingRanoreAppFolder TestAutomationForGUITestingRanore
        {
            get { return _testautomationforguitestingranore; }
        }

        /// <summary>
        /// The TestAutomationForGUITestingRanore1 folder.
        /// </summary>
        [RepositoryFolder("5c6d7862-6dc5-4e00-95a7-444c822144d3")]
        public virtual TestExpoDemoRepositoryFolders.TestAutomationForGUITestingRanore1AppFolder TestAutomationForGUITestingRanore1
        {
            get { return _testautomationforguitestingranore1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class TestExpoDemoRepositoryFolders
    {
        /// <summary>
        /// The TestAutomationForGUITestingRanoreAppFolder folder.
        /// </summary>
        [RepositoryFolder("07b82945-4f59-4eb8-a006-10e9904e3f63")]
        public partial class TestAutomationForGUITestingRanoreAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _downloadtrialbuttonInfo;
            RepoItemInfo _formfirstnameInfo;
            RepoItemInfo _formlastnameInfo;
            RepoItemInfo _formemailInfo;
            RepoItemInfo _registerInfo;
            RepoItemInfo _iconexitInfo;
            RepoItemInfo _tellusmoreaboutyourselfInfo;

            /// <summary>
            /// Creates a new TestAutomationForGUITestingRanore  folder.
            /// </summary>
            public TestAutomationForGUITestingRanoreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestAutomationForGUITestingRanore", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "07b82945-4f59-4eb8-a006-10e9904e3f63", "")
            {
                _downloadtrialbuttonInfo = new RepoItemInfo(this, "DownloadTrialButton", ".//div[#'c14071']/?/?/a[@innertext='Download Trial']", 30000, null, "684aed8b-ce9b-461f-af3c-1518ed820dc1");
                _formfirstnameInfo = new RepoItemInfo(this, "FormFirstName", ".//input[#'form-FirstName']", 30000, null, "21b41489-a3ba-41f7-a578-8f36ba92f628");
                _formlastnameInfo = new RepoItemInfo(this, "FormLastName", ".//input[#'form-LastName']", 30000, null, "8db5321d-c96c-4b82-b143-2a1616dd3552");
                _formemailInfo = new RepoItemInfo(this, "FormEmail", ".//input[#'form-Email']", 30000, null, "c5a6a128-c782-4be5-8f60-f9f1179bca90");
                _registerInfo = new RepoItemInfo(this, "Register", ".//fieldset[#'first-form']/?/?/button[@innertext='Register']", 30000, null, "dcd307f3-19b9-469b-b836-ebea3a829702");
                _iconexitInfo = new RepoItemInfo(this, "IconExit", ".//fieldset[#'second-form']//span", 30000, null, "d9f04c70-369b-45f6-bbf6-0211c70e4c42");
                _tellusmoreaboutyourselfInfo = new RepoItemInfo(this, "TellUsMoreAboutYourself", ".//fieldset[#'second-form']//span[@innertext~'^Tell\\ us\\ more\\ about\\ yourse']", 30000, null, "d561959d-6f61-4f86-ae65-6cf5e7ed8879");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("07b82945-4f59-4eb8-a006-10e9904e3f63")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("07b82945-4f59-4eb8-a006-10e9904e3f63")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DownloadTrialButton item.
            /// </summary>
            [RepositoryItem("684aed8b-ce9b-461f-af3c-1518ed820dc1")]
            public virtual Ranorex.ATag DownloadTrialButton
            {
                get
                {
                    return _downloadtrialbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DownloadTrialButton item info.
            /// </summary>
            [RepositoryItemInfo("684aed8b-ce9b-461f-af3c-1518ed820dc1")]
            public virtual RepoItemInfo DownloadTrialButtonInfo
            {
                get
                {
                    return _downloadtrialbuttonInfo;
                }
            }

            /// <summary>
            /// The FormFirstName item.
            /// </summary>
            [RepositoryItem("21b41489-a3ba-41f7-a578-8f36ba92f628")]
            public virtual Ranorex.InputTag FormFirstName
            {
                get
                {
                    return _formfirstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FormFirstName item info.
            /// </summary>
            [RepositoryItemInfo("21b41489-a3ba-41f7-a578-8f36ba92f628")]
            public virtual RepoItemInfo FormFirstNameInfo
            {
                get
                {
                    return _formfirstnameInfo;
                }
            }

            /// <summary>
            /// The FormLastName item.
            /// </summary>
            [RepositoryItem("8db5321d-c96c-4b82-b143-2a1616dd3552")]
            public virtual Ranorex.InputTag FormLastName
            {
                get
                {
                    return _formlastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FormLastName item info.
            /// </summary>
            [RepositoryItemInfo("8db5321d-c96c-4b82-b143-2a1616dd3552")]
            public virtual RepoItemInfo FormLastNameInfo
            {
                get
                {
                    return _formlastnameInfo;
                }
            }

            /// <summary>
            /// The FormEmail item.
            /// </summary>
            [RepositoryItem("c5a6a128-c782-4be5-8f60-f9f1179bca90")]
            public virtual Ranorex.InputTag FormEmail
            {
                get
                {
                    return _formemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FormEmail item info.
            /// </summary>
            [RepositoryItemInfo("c5a6a128-c782-4be5-8f60-f9f1179bca90")]
            public virtual RepoItemInfo FormEmailInfo
            {
                get
                {
                    return _formemailInfo;
                }
            }

            /// <summary>
            /// The Register item.
            /// </summary>
            [RepositoryItem("dcd307f3-19b9-469b-b836-ebea3a829702")]
            public virtual Ranorex.ButtonTag Register
            {
                get
                {
                    return _registerInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Register item info.
            /// </summary>
            [RepositoryItemInfo("dcd307f3-19b9-469b-b836-ebea3a829702")]
            public virtual RepoItemInfo RegisterInfo
            {
                get
                {
                    return _registerInfo;
                }
            }

            /// <summary>
            /// The IconExit item.
            /// </summary>
            [RepositoryItem("d9f04c70-369b-45f6-bbf6-0211c70e4c42")]
            public virtual Ranorex.SpanTag IconExit
            {
                get
                {
                    return _iconexitInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The IconExit item info.
            /// </summary>
            [RepositoryItemInfo("d9f04c70-369b-45f6-bbf6-0211c70e4c42")]
            public virtual RepoItemInfo IconExitInfo
            {
                get
                {
                    return _iconexitInfo;
                }
            }

            /// <summary>
            /// The TellUsMoreAboutYourself item.
            /// </summary>
            [RepositoryItem("d561959d-6f61-4f86-ae65-6cf5e7ed8879")]
            public virtual Ranorex.SpanTag TellUsMoreAboutYourself
            {
                get
                {
                    return _tellusmoreaboutyourselfInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TellUsMoreAboutYourself item info.
            /// </summary>
            [RepositoryItemInfo("d561959d-6f61-4f86-ae65-6cf5e7ed8879")]
            public virtual RepoItemInfo TellUsMoreAboutYourselfInfo
            {
                get
                {
                    return _tellusmoreaboutyourselfInfo;
                }
            }
        }

        /// <summary>
        /// The TestAutomationForGUITestingRanore1AppFolder folder.
        /// </summary>
        [RepositoryFolder("5c6d7862-6dc5-4e00-95a7-444c822144d3")]
        public partial class TestAutomationForGUITestingRanore1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new TestAutomationForGUITestingRanore1  folder.
            /// </summary>
            public TestAutomationForGUITestingRanore1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestAutomationForGUITestingRanore1", "/form[@title~'^Test\\ Automation\\ for\\ GUI\\ T']", parentFolder, 30000, null, true, "5c6d7862-6dc5-4e00-95a7-444c822144d3", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", ".//tabpage/button[@accessiblename='Close']", 30000, null, "01b02848-cc05-4dda-8fa7-d6955c7f7689");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5c6d7862-6dc5-4e00-95a7-444c822144d3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c6d7862-6dc5-4e00-95a7-444c822144d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("01b02848-cc05-4dda-8fa7-d6955c7f7689")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("01b02848-cc05-4dda-8fa7-d6955c7f7689")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}